import styles from "../../styles/Kahoot.module.css";
import Head from "next/head";
import Footer from "../components/footer";
import {useEffect} from "react";
import Header from "../components/header";

const guide = {
    "title":"Com Accedir",
    "body":
        [
            {
                "type":"text",
                "text":["Els fulls de càlcul de Google són una eina que et permet fer gràfics, operacions i ordenar informació."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Per entrar, ho pots fer des del cercador o el panel d’eines de Google. Un cop a dins, per crear un full de càlcul has de clicar el botó de “+” que surt a dalt a l’esquerra."],
                "newline":1
            }
        ]
};
let guideHTML = "";

export default function KahootCreate() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (var i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title.text}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}