import styles from "../../../styles/Kahoot.module.css";
import Head from "next/head";
import Footer from "../../components/footer";
import {useEffect} from "react";
import Header from "../../components/header";

const guide = {
    "title":"Gràfics",
    "body":
        [
            {
                "type":"image",
                "location":"/images/google/sheets/excel1.png"
            },
            {
                "type":"text",
                "text":["Per fer un gràfic, posarem les dades necessàries com a l’exemple, les seleccionarem i a continuació, a l’apartat %Insereix% pressionarem el botó %Gràfic%."],
                "newline":1
            },
            {
                "type":"text",
                "text":["El gràfic ja està creat. Si voleu saber més sobre com editar-lo un cop fet, us deixem un vídeo ----> <a href='https://www.youtube.com/watch?v=siy-pgW23hU'>aqui</a> <----"],
                "newline":1
            }
        ]
};
let guideHTML = "";

export default function GoogleSheetsGraph() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (var i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title.text}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}