import Head from 'next/head'
import styles from '../../../styles/Kahoot.module.css'
import Footer from "../../components/footer";
import Header from "../../components/header";

export default function sheets() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Kahoot</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Kahoot
                </h1>

                <div className={styles.grid}>
                    <a href='sheets/entrar' rel="noreferrer">
                        <div className={styles.card}>
                            <h2>Accedir</h2>
                            <h4>Entra a Google Sheets</h4>
                        </div>
                    </a>
                    <a href='sheets/grafics' rel="noreferrer">
                        <div className={styles.card}>
                            <h2>Crear Gràfics</h2>
                            <h4>Aprèn a fer els teus propis gràfics</h4>
                        </div>
                    </a>
                    <a href='sheets/operacions' rel="noreferrer">
                        <div className={styles.card}>
                            <h2>Fer Operacions</h2>
                            <h4>Fes operacions matemàtiques amb Google Sheets</h4>
                        </div>
                    </a>
                </div>
            </main>

            <Footer />
        </div>
    )
}
