import styles from "../../../styles/Kahoot.module.css";
import Head from "next/head";
import Footer from "../../components/footer";
import {useEffect} from "react";
import Header from "../../components/header";

const guide = {
    "title":"Operacions",
    "body":
        [
            {
                "type":"text",
                "text":["Si el que volem és fer operacions matemàtiques per ordenar nombres podem fer això:"],
                "newline":1
            },
            {
                "type":"image",
                "location":"/images/google/excel/excel2.png.png"
            },
            {
                "type":"text",
                "text":["Al col·locar una filera de nombres i seleccionar-los, si cliquem a l’últim botó de a dalt a la dreta i després a %SUM%, just al bloc de a baix dels nombres sortirà una suma dels anteriors."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Els botons %AVERAGE%, %MAX% i %MIN%, fan la mitja o et diuen el màxim o mínim respectivament. Sobre els nombres seleccionats."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Els fulls de càlcul són una eina difícil d’utilitzar i amb moltes i moltes opcions."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Per això no ho podem explicar tot, aquí hem explicat les funcions més útils per a l’escola."],
                "newline":1
            }
        ]
};
let guideHTML = "";

export default function GoogleSheetsOperations() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (var i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title.text}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}