import Head from 'next/head'
import styles from '../../../styles/Google.module.css'
import Footer from "../../components/footer";
import Header from "../../components/header";
import {useEffect} from "react";

const guide = {

    "title":"Redactar un Correu i col·locar un enllaç",
    "body":
        [

            {
                "type":"text",
                "text":["Un cop a dins, per enviar un correu has de pressionar el botó de dalt a l’esquerra %REDACTA%."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Ara, per redactar has de:"],
                "newline":1
            },
            {
                "type":"text",
                "text":["Escriure a qui li vols enviar. Una o més persones."],
                "newline":1
            },
            {
                "type":"text",
                "text":["Posar-li un títol, a l’assumpte."],
                "newline":1
            },
            {
                "type":"text",
                "text":["I escriure’l, a la part de a baix."],
                "newline":2
            },
            {
                "type":"text",
                "text":["Si vols posar un enllaç, pots copiar-lo al text i amb aquest botó de a baix, fer que es pugui clicar."],
                "newline":1
            },
            {
                "type":"image",
                "location": "/images/google/gmail/gmaillink.png"
            },
            {
                "type":"text",
                "text":["Hi ha més opcions, però no totes són importants."]
            }
        ]
};

let guideHTML = "";

export default function GoogleGmailRedactar() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (var i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}