import Head from 'next/head'
import styles from '../../../styles/Google.module.css'
import Footer from "../../components/footer";
import Header from "../../components/header";
import {useEffect} from "react";

const guide = {
    "title": "Crear un formulari",
    "body": [
        {
            "type": "text",
            "text": [
                "A l’entrar, si pressiones el botó de %+%, començaràs a crear el teu formulari.",
                "Només entrar, pots escriure un títol i fer la primera pregunta."
            ],
            "newline": 2
        },
        {
            "type": "text",
            "text": [
                "A l’hora de formular les preguntes es poden fer diverses coses per editar-les:"
            ],
            "newline": 1
        },
        {
            "type": "image",
            "location": "/images/google/forms/forms1.png"
        },
        {
            "type": "text",
            "text": [
                "A la pregunta se li ha de posar títol i escriure les preguntes."
            ],
            "newline": 1
        },
        {
            "type": "text",
            "text": [
                " Si cliquem el botó que posa “Selecció múltiple”, es despleguen moltes opcions per editar les preguntes: "
            ]
        },
        {
            "type": "text",
            "text": [
                " Si cliquem el botó que posa “Selecció múltiple”, es despleguen moltes opcions per editar les preguntes: Els dos primers fan que la resposta sigui de text, llarg o curt.Els següents tres, fan que puguis triar només una resposta, varies o que es desplegui una pestanya i només puguis triar un. El següent, pujar un fitxer per a la pregunta. I els tres que venen a continuació, són per fer graelles amb una resposta per línia."]

        },
        {
            "type": "text",
            "text": [
                " Els botons de la dreta serveixen per crear una nova pregunta, importar preguntes d’un altre lloc, afegir, text, imatges, vídeos. L’últim crea una nova secció per ordenar les preguntes. A dalt de tot, hi ha la pestanya respostes, on et surten les respostes de la gent al formulari. I a configuració, pots canviar les opcions d'edició del formulari. Per enviar per correu el nostre formulari a algú pressiona el botó “Envia” de a dalt a la dreta i escriure el correu del destinatari."]

},
]
};

let guideHTML = "";

export default function GoogleGmailRedactar() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (let i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}