import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Google.module.css'

export default function Google() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Google</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Google
                </h1>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <img src="/logos_serveis/google.png" alt='Logo Google' height='100' width='100' />
                        <h2>Google &rarr;</h2>
                    </a>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <img src="/logos_serveis/kahoot.png" alt='Logo Kahoot' height='100' width='100' />
                        <h2>Kahoot &rarr;</h2>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                Gracies a{':'} <br/>
                <div>
                    <a href='https://dinahosting.com' target='_blank' rel="noreferrer">
                        <span className={styles.logo}>
                            <Image src="/images/dinahosting.png" alt="Logo DinaHosting" width={72} height={16} />
                        </span>
                    </a>
                    <a href='https://wapps.cat' target='_blank' rel="noreferrer">
                        <span className={styles.logo}>
                            <Image src="/images/wapps.png" alt="Logo Wapps" width={72} height={16} />
                        </span>
                    </a>
                </div>
            </footer>
        </div>
    )
}
