import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Google.module.css'

function openInNewTab(url) {
    url = 'https://' + url;
    window.open(url, '_blank').focus()
}

export default function Google() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Google</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Google
                </h1>

                <div className={styles.grid}>
                    <div onClick="window.open('http://google.pl', '_blank');" className={styles.card}>
                        <img src="/logos_serveis/sheets.png" alt='Logo Sheets' height='100' width='100' />
                        <h2>Sheets &rarr;</h2>
                    </div>
                    <div onClick="window.open('http://google.pl', '_blank');" className={styles.card}>
                        <img src="/logos_serveis/docs.png" alt='Logo Docs' height='70' width='70' />
                        <h2>Docs &rarr;</h2>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                Gracies a{':'} <br/>
                <div>
                    <a href='https://dinahosting.com' target='_blank' rel="noreferrer">
                        <span className={styles.logo}>
                            <Image src="/images/dinahosting.png" alt="Logo DinaHosting" width={72} height={16} />
                        </span>
                    </a>
                    <a href='https://wapps.cat' target='_blank' rel="noreferrer">
                        <span className={styles.logo}>
                            <Image src="/images/wapps.png" alt="Logo Wapps" width={72} height={16} />
                        </span>
                    </a>
                </div>
            </footer>
        </div>
    )
}
