import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Kahoot.module.css'
import Footer from "../components/footer";

export default function Index() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Kahoot</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Google
                </h1>

                <div className={styles.grid}>
                    <a href='kahoot/guide?id=devtest' rel="noreferrer">
                        <div className={styles.card}>
                            <Image src="/logos_serveis/sheets.png" alt='Logo Sheets' height='100' width='100' />
                            <h2>Sheets &rarr;</h2>
                        </div>
                    </a>
                    <a href='google/docs' rel="noreferrer">
                        <div className={styles.card}>
                            <Image src="/logos_serveis/docs.png" alt='Logo Docs' height='100' width='80' />
                            <h2>Docs &rarr;</h2>
                        </div>
                    </a>
                </div>
            </main>

            <Footer />
        </div>
    )
}
