import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Kahoot.module.css'
import Footer from "../components/footer";

export default function Kahoot() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Kahoot</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Kahoot
                </h1>

                <div className={styles.grid}>
                    <a href='kahoot/guide?id=devtest' rel="noreferrer">
                        <div className={styles.card}>
                            <h2>Crear un Compte i Iniciar Sessió</h2>
                            <h4>Prepara Kahoot per fer-lo servir</h4>
                        </div>
                    </a>
                    <a href='google/docs' rel="noreferrer">
                        <div className={styles.card}>
                            <h2>Crear un Kahoot</h2>
                            <h4>Comença a fer servir Kahoot</h4>
                        </div>
                    </a>
                </div>
            </main>

            <Footer />
        </div>
    )
}
