import styles from "../../styles/Kahoot.module.css";
import Head from "next/head";
import Footer from "../components/footer";
import {useEffect} from "react";

const guide = {
    "title": {
        "text": "Crear un compte i iniciar sessió",
        "size": 24
    },
    "body": [
        {
            "text": ["Només entrar a la web, veuràs aquesta pantalla. Per crear una conta hauràs de presionar el botó verd d’adalt a la dreta que té escrit %Sign Up% o %Registrarse%."],
            "type": "text",
            "newline": 1
        },
        {
            "type": "image",
            "location": "/images/kahoot/register.png"
        },
        {
            "type": "text",
            "text": ["Aquest botó et portarà a una pantalla on et demanarà el tipus de conta. Tria %Estudiante%."],
            "newline" : 1
        },
        {
            "type" : "text",
            "text" : ["Ara, a la següent pantalla introdueix el teu mes i dia de naixement. A l’apartat de l’any posa un anterior al 2002, com el 1995, per exemple."],
            "newline" : 1
        },
        {
            "type" : "text",
            "text" : ["A continuació escriu el teu nom d’usuari, serà el nom que et representi. Ha de identificar-te. Per exemple si et dius Pep Garcia, el teu nom podria ser PGarcia08."],
            "newline" : 2
        },
        {
            "type" : "text",
            "text" : ["A continuació només hauràs d’apretar el botó %Continuar con Google%."],
            "newline" : 1
        },
        {
            "type" : "image",
            "location" : "/images/kahoot/register2.png"
        },
        {
            "type" : "text",
            "text" : ["Ara que ja tens una conta creada, si vols iniciar sessió, només hauràs de presionar el botó %iniciar sesión% i clicar a %Continuar con Google%."],
            "newline" : 1
        }

    ]

}

let guideHTML = "";

export default function KahootLogin() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (var i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title.text}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title.text}
                </h1>
                <div id='guideContainer'></div>

            </main>

            <Footer />
        </div>
    )
}