import Head from 'next/head'
import styles from '../../../styles/Google.module.css'
import Footer from "../../components/footer";
import Header from "../../components/header";
import {useEffect} from "react";

const guide = {
        "title":"Drive és una eina que et permet crear, compartir i treballar amb documents, taules o presentacions.",
        "body": [
            {
                "type":"text",
                "text":["Ara explicarem com funciona l’eina i les funcions essencials"],
                "newline":1
            },
            {
                "type":"text",
                "text":["Per entrar es pot fer cercant-lo a Google o per l’espai d’eines situat a dalt a la dreta en la pantalla d’inici de Google."],
                "newline":1
            },
            {
                "type":"text",
                "text":["A Drive, només entrar hi ha moltes opcions possibles. Explicarem les més necessàries:"],
                "newline":1
            },
            {
                "type":"image",
                "location":"/images/google/drive/flechitas1.png"
            },
            {
                "type":"text",
                "text": ["El primer botó, %Prioritat%, és on pots veure el que el programa identifica com a què és important ara mateix. És una de les opcions menys útils, però sempre està bé tenir-la."],
        "newline":1
    },
    {
        "type": "text",
        "text":["El segon botó, %La Meva Unitat%, és possiblement el més rellevant, és on trobem tots els nostres documents. Si no trobes un el pots cercar per la barra de cerca a la part superior."],
"newline":1
},
{
    "type":"text",
    "text": ["El tercer,%Compartit amb Mi%, és on veiem tots els arxius que ens han compartit altres persones."],
    "newline":1
},
{
    "type":"text",
    "text": ["El Quart botó, %Recents%, és molt important també. Aquí estan els arxius que hem utilitzat recentment. Aquest apartat t’ajuda a seguir treballs de dies anteriors."],
    "newline":1
},
{
    "type": "text",
    "text": ["El Cinquè, %Destacats%, només és útil per a la gent que li agradi tenir tot ordenat. Aquí acaben tots els arxius que marquis com a destacats. El Sisè i últim, %Paperera%, és on es troben tots els arxius eliminats. Des d’aquí els pots recuperar o borrar-los per a sempre."],
    "newline":1

},
{
    "type":"text",
    "text": ["L’última opció és el botó %+% o %Nou%. Des d'aquest crearem tots els nostres arxius, ja siguin documents, fulls de càlcul, presentacions o formularis."],
    "newline":1
},
{
    "type":"image",
    "location":"/images/google/drive/iconosdrive.png"
},
{
    "type":"text",
    "text": ["Un cop pressionat aquest botó, trobem moltes opcions."],
    "newline":1
},
{
    "type":"text",
    "text": ["%Carpeta%, crear una nova carpeta al Drive, on posar arxius per tenir-los ordenats. %Penja fitxers% i %Penja carpeta% serveixen per pujar arxius de l’ordinador per a tenir-los al Drive."],
    "newline":1

},
{
    "type":"text",
    "text":["%Documents%, %Fulls de Càlcul%, %Presentacions% i %Formularis% serveixen per crear un arxiu de cada tipus respectivament."],
    "newline":1
},
{
    "type":"text",
    "text":["Passant el cursor per sobre de %Més%”, surten moltes més opcions com dibuixos, diagrames i pissarres entre d’altres."],
}
]
}




let guideHTML = "";

export default function GoogleGmailRedactar() {
    useEffect(() => {
        guide.body.forEach(item => {
            if (item.type === 'image') {
                guideHTML = guideHTML + "<Image src='" + item.location + "' width='inherit - 10%' height='auto' />"
            }

            if (item.type === 'text') {
                item.text.forEach(textie => {
                    textie = textie.split('%').join('"').split('&').join(':');
                    guideHTML = guideHTML + textie + ' ';
                });

                for (let i = 0; item.newline < i; i++) {
                    guideHTML = guideHTML + "<br />"
                }
            }
        })
        document.getElementById('guideContainer').innerHTML = guideHTML
    }, []);

    return(
        <div className={styles.container}>
            <Head>
                <title>{guide.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main className={styles.main}>
                <h1 className={styles.title}>
                    {guide.title}
                </h1>
                <div id='guideContainer'/>

            </main>

            <Footer />
        </div>
    )
}